#include "lvgl.h"

/*
 * Placeholder 1×1 transparent A8 images.
 * Replace with real assets generated by LVGLImage.py (see images.h).
 */

static const uint8_t img_wifi_data[] = { 0x00 };

const lv_image_dsc_t img_wifi = {
    .header = {
        .cf        = LV_COLOR_FORMAT_A8,
        .magic     = LV_IMAGE_HEADER_MAGIC,
        .flags     = 0,
        .w         = 1,
        .h         = 1,
        .stride    = 1,
    },
    .data_size = 1,
    .data      = img_wifi_data,
};

static const uint8_t img_broadcast_data[] = { 0x00 };

const lv_image_dsc_t img_broadcast = {
    .header = {
        .cf        = LV_COLOR_FORMAT_A8,
        .magic     = LV_IMAGE_HEADER_MAGIC,
        .flags     = 0,
        .w         = 1,
        .h         = 1,
        .stride    = 1,
    },
    .data_size = 1,
    .data      = img_broadcast_data,
};
