#pragma once

#include "lvgl.h"

/*
 * §3 — Font configuration.
 *
 * Real fonts: IBM Plex Mono Bold, generated with lv_font_conv:
 *
 *   lv_font_conv --font IBMPlexMono-Bold.ttf --size 12 --bpp 4 \
 *     --format lvgl --no-compress -r 0x20-0x5A -o font_mono_12.c
 *
 *   lv_font_conv --font IBMPlexMono-Bold.ttf --size 14 --bpp 4 \
 *     --format lvgl --no-compress -r 0x20-0x7A -o font_mono_14.c
 *
 *   lv_font_conv --font IBMPlexMono-Bold.ttf --size 68 --bpp 4 \
 *     --format lvgl --no-compress -r 0x30-0x39 -o font_mono_68.c
 *
 * Place the generated .c files in ui/fonts/ and set USE_PLACEHOLDER_FONTS=0
 * in lv_conf.h (or as a compiler define) to switch to real assets.
 * Also requires LV_FONT_MONTSERRAT_12=1, LV_FONT_MONTSERRAT_14=1,
 * LV_FONT_MONTSERRAT_48=1 in lv_conf.h for the placeholder path.
 *
 * NOTE: lv_font_montserrat_48 ≠ 68 px. The numeral RIGHT_MID offsets
 * (-64, +6) are tuned for the real 68 px font and will look off under
 * placeholders. This is expected.
 */

#ifndef USE_PLACEHOLDER_FONTS
#define USE_PLACEHOLDER_FONTS 1
#endif

#if USE_PLACEHOLDER_FONTS
/* Placeholder: map to nearest LVGL built-ins for development builds */
#define font_mono_12 lv_font_montserrat_12
#define font_mono_14 lv_font_montserrat_14
#define font_mono_68 lv_font_montserrat_48
#else
/* Production: IBM Plex Mono Bold, generated by lv_font_conv */
LV_FONT_DECLARE(font_mono_12);
LV_FONT_DECLARE(font_mono_14);
LV_FONT_DECLARE(font_mono_68);
#endif
